<a href="https://colab.research.google.com/github/OlegAndrienko/GOIT_HW11/blob/main/%D0%9A%D0%BE%D0%BF%D1%96%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BD%D0%B8%D0%BA%D0%B0_%22Hw1_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


In [3]:
v = np.arange(0, 10)

In [4]:
print(v)

[0 1 2 3 4 5 6 7 8 9]


# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [5]:
A = np.zeros((3, 3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [6]:
B = np.random.randint(1, 10, (5, 5))
print(B)

[[2 5 1 5 2]
 [8 8 2 4 4]
 [8 6 3 3 1]
 [1 7 8 1 6]
 [7 4 4 8 4]]


# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.



In [7]:
C = np.random.random((4, 4))
print(C)

[[0.42631236 0.12328244 0.06517504 0.40559089]
 [0.75969914 0.98717608 0.95325856 0.22552441]
 [0.34078684 0.20040285 0.32683264 0.41992701]
 [0.75349983 0.99239165 0.32411456 0.65412312]]


# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [8]:
D = np.random.randint(1, 10, 5)
E = np.random.randint(1, 10, 5)
print(D)
print(E)
print(D+E)
print(D-E)
print(D*E)

[3 7 2 2 2]
[8 9 2 3 6]
[11 16  4  5  8]
[-5 -2  0 -1 -4]
[24 63  4  6 12]


# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [9]:
F = np.random.randint(1, 10, 7)
G = np.random.randint(1, 10, 7)
print(F)
print(G)
print(np.dot(F, G))

[5 3 2 1 4 6 2]
[8 4 7 6 8 8 5]
162


# 7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.



In [12]:
H = np.random.randint(1, 10, (2, 2)) # 1-10, 2x2
I = np.random.randint(1, 10, (2, 3)) # 1-10, 2x3
print(H)
print(I)
print(np.dot(H, I))

[[3 7]
 [2 8]]
[[5 3 8]
 [6 7 2]]
[[57 58 38]
 [58 62 32]]


# 8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [13]:
J = np.random.randint(1, 10, (3, 3))
print(J)
print(np.linalg.inv(J))

[[3 9 6]
 [8 1 2]
 [2 2 5]]
[[-0.00421941  0.13924051 -0.05063291]
 [ 0.15189873 -0.01265823 -0.17721519]
 [-0.05907173 -0.05063291  0.29113924]]


# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [14]:
K = np.random.random((4, 4))
print(K)
print(K.T)

[[0.95096432 0.86938598 0.11105045 0.96282646]
 [0.55600294 0.96062125 0.05986713 0.96269645]
 [0.10157109 0.93290188 0.60776137 0.30074621]
 [0.62527193 0.90791008 0.47133497 0.96417381]]
[[0.95096432 0.55600294 0.10157109 0.62527193]
 [0.86938598 0.96062125 0.93290188 0.90791008]
 [0.11105045 0.05986713 0.60776137 0.47133497]
 [0.96282646 0.96269645 0.30074621 0.96417381]]


#10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [15]:
L = np.random.randint(1, 10, (3, 4))
v = np.random.randint(1, 10, 4)
print(L)
print(v)
print(np.dot(L, v))

[[6 9 6 1]
 [4 7 1 4]
 [6 6 4 2]]
[8 8 2 6]
[138 114 116]


# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [16]:
M = np.random.random((2, 3))
v = np.random.random(3)
print(M)
print(v)
print(np.dot(M, v))

[[0.6493235  0.6998773  0.65664048]
 [0.73223115 0.14842565 0.08685232]]
[0.7307871  0.56810868 0.03569847]
[0.89556467 0.62252747]


# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [17]:
N = np.random.randint(1, 10, (2, 2))
O = np.random.randint(1, 10, (2, 2))
print(N)
print(O)
print(N*O)

[[2 9]
 [2 7]]
[[2 4]
 [5 1]]
[[ 4 36]
 [10  7]]


# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.


In [18]:
P = np.random.randint(1, 10, (2, 2))
Q = np.random.randint(1, 10, (2, 2))
print(P)
print(Q)
print(np.dot(P, Q))

[[3 9]
 [3 5]]
[[5 8]
 [3 9]]
[[ 42 105]
 [ 30  69]]


# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [19]:
R = np.random.randint(1, 100, (5, 5))
print(R)
print(np.sum(R))

[[ 7 58 30 69 69]
 [59 32 11 23 57]
 [97 67 32 66 18]
 [ 2 85 30 26 27]
 [61  6 81 99 17]]
1129


# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [20]:
S = np.random.randint(1, 10, (4, 4))
T = np.random.randint(1, 10, (4, 4))
print(S)
print(T)
print(S-T)

[[7 7 4 9]
 [4 7 6 6]
 [7 4 4 8]
 [6 9 2 4]]
[[1 1 8 2]
 [2 6 9 4]
 [4 7 1 7]
 [1 6 6 2]]
[[ 6  6 -4  7]
 [ 2  1 -3  2]
 [ 3 -3  3  1]
 [ 5  3 -4  2]]


# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [21]:
U = np.random.random((3, 3))
print(U)
print(U.sum(axis=1))

[[0.81975328 0.46102862 0.481684  ]
 [0.30558703 0.16705588 0.36111944]
 [0.22662259 0.8048062  0.59555164]]
[1.76246591 0.83376234 1.62698043]


# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [22]:
V = np.random.randint(1, 10, (3, 4))
print(V)
print(np.square(V))

[[3 5 2 2]
 [5 2 8 9]
 [6 4 5 5]]
[[ 9 25  4  4]
 [25  4 64 81]
 [36 16 25 25]]


# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [23]:
W = np.random.randint(1, 50, 4)
print(W)
print(np.sqrt(W))

[ 5 16 38 21]
[2.23606798 4.         6.164414   4.58257569]
